FROM node:14.17-alpine

WORKDIR /app

RUN apk add \
    ffmpeg \
    git \
    python3

COPY package*.json ./
COPY etc etc
COPY lib lib
COPY bin bin
COPY assets assets
COPY migrations migrations
COPY app.js ./
COPY runner.js ./
COPY babel.config.js ./
COPY .sequelizerc ./
COPY .env.defaults ./

RUN npm ci

CMD ./bin/wait.sh && npm run migration:dev && npm run start:dev
